language: node_js
node_js:
    - 9.11
script:
    - npm run ci
deploy:
    - provider: script
      script: npm run zip && npm run deploy
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ staging
